---
title: "Instructor's corner"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
---

<html lang="en">

<br>


# Supplies needed for labs

| Source | Number per student | Total number for FISH 406 | Item |
| :------- | :------: | :------: | -------: |
| general teaching supplies | 1 | 24 | stereomicroscope + illumination |
| general teaching supplies | 0.5 | 12 | compound microscope |
| general teaching supplies | 1 pair per class | several boxes of each size | nitrile gloves |
| general teaching supplies | 1 | 24 | dissecting trays with wax |
| general teaching supplies | many | several boxes | dissecting pins |
| general teaching supplies | many | several boxes | microscope slides |
| general teaching supplies | many | several boxes | cover slips |
| general teaching supplies | 1 | 24 | scalpel handles |
| general teaching supplies | 1 | several boxes | #10 scalpel blades |
| general teaching supplies | 1 | 24 | coarse dissecting scissors |
| general teaching supplies | 1 | 24 | fine dissecting scissors |
| general teaching supplies | 2 | 48 | forceps |
| general teaching supplies | 1 | 24 | probes |
| general teaching supplies | 1 | 1 box | plastic pipettes |
| general teaching supplies | 1 | 1 box | glass pipettes |
| general teaching supplies | 1 | 24 | pipette bulbs |
| general teaching supplies | 1 | 24 | small glass beakers |
| general teaching supplies | 2 | 48 | Syracuse dishes (heavy-bottomed, shallow glass dishes) |
| general teaching supplies | 2 | 48 | watch glasses |
| general teaching supplies | 0.5 | 12 | glass dishes with divots for holding small specimens in fluid |
| general teaching supplies | 1 | 24 | plastic calipers |
| general teaching supplies | 1 | 24 | 12" rulers |
| general teaching supplies | 1 | 24 | 6" rulers |
| general teaching supplies | 0.5 | 12 | squeeze bottles |
| general teaching supplies | shared | 1 for each lab table | spray bottle of bleach |
| general teaching supplies | shared | 1 for each lab table | spray bottle of cleaning solution |
| general teaching supplies | shared | 1 for each sink | hand soap |
| general teaching supplies | shared | a bunch | paper towels |
| general teaching supplies | shared | 4 | red biohazard bags |
| obtained new each year | 1 | as many as requested | empty three-ring binders |
| obtained new each year | shared | 1 ream | white printer paper |
| obtained new each year | 0.5 | 24 | schistosome-infected mice from BRI Resources / NIH |
| obtained new each year | shared | a bucket | seawater |
| obtained new each year | 0.5 | 24 | whole, ungutted, wild fish from the seafood market |
| obtained new each year | 0.5 | 24 | 1 small can of wild salmon |
| obtained new each year | 1 | 48 | *Hemigrapsus oregonensis* and *H. nudus* collected from Tacoma Narrows, WA |
| obtained new each year | shared | 2 | batch of 100 living termites from Carolina Biological Supply |
| obtained new each year | shared | several | poop samples from several dog individuals (with metadata on dogs) |
| obtained new each year | shared | several | poop samples from several elk/deer/cougar/otter individuals (with metadata on hosts) |
| parasitology teaching supplies | shared | shared | three-hole punch |
| parasitology teaching supplies | shared | a few boxes | colored pencils |
| parasitology teaching supplies | shared | 500 mL | mammal Ringer's solution |
| parasitology teaching supplies | shared | 500 mL | insect Ringer's solution |
| parasitology teaching supplies | 1 | 24 | lunch trays |
| parasitology teaching supplies | 2 | 48 | glass squash plates |
| parasitology teaching supplies | 1 | 48 | preserved *Ascaris* spp. nematodes |
| parasitology teaching supplies | 1 | 48 | fecalyzers |
| parasitology teaching supplies | shared | 1 gallon | zinc sulfate solution for fecalyzers |
| parasitology teaching supplies | shared | 1 container | mineral oil |
| parasitology teaching supplies | shared | 4 | immersion oil |
| parasitology teaching supplies | shared | 4 | hammer |

<br>

# Class agendas

## Class 1

Agenda:

* instructor introduces herself and any TAs
* reminder about class meetings (labs, holidays) coming up this week
* reminder to turn on Canvas notifications
* instructor relays the story of how she got interested in parasites
* instructor invites students to introduce themselves
* instructor reviews course website
* instructor reviews Canvas page
* instructor reviews class norms
* PollEverywhere questions
* in-class activities shown in class_1.ppt

<br>

## Class 2

Agenda:

* summarize Lab 1
* remind students to take Qualtrics survey
* remind students about weekly quizzes via Canvas
* in-class activities shown in class_2.ppt

<br>

## Class 3

Agenda:

* remind students to take week 1 quiz
* contextualize Parasites Without Borders videos - students are responsible for the ecology parts, not the medicine (don't worry about drug dosages!)
* they just watched videos with me playing the flute - mention that!
* introduce variationson theme, relate from music to parasites
* in-class activities shown in class_3.ppt

<br>

## Class 4

Agenda:

* introduce term project, encourage students to start thinking about what ecological question they might like to answer, remind them to do the *How to Do Ecology* readings
* remind students about weekly quizzes
* context for today's activities on schistosomes: parasites are cool but they also do terrible things to real people
* schistosomiasis is a disease where aquatic ecology and public health meet
* in-class activities shown in class_4.ppt

<br>

## Class 5

Agenda:

* remind students to use nametags so that instructor can learn everyone's name
* recap yesterday's lab, ask students which parasites they saw
* remind students about weekly quizzes
* remind students [where to find information about term project on the course website](https://wood-lab.github.io/fish_406/assignments.html#Term_project)
* remind students that the *How to Do Ecology* readings will help them with the term project
* take a survey of students' preferred podcasts and recommend [This Week in Parasitism](https://www.microbe.tv/twip/about) for review
* introduce Chelsea's work on schistosomiasis in Senegal, explain the motivation (aquatic ecology in service of public health)
* in-class activities shown in class_5.ppt

<br>

## Class 6

Agenda:

* show students the PLOT OF FEAR: fear_of_parasites ~ knowledge_of_parasites
* remind students about week 2 quiz, due today at 11:59pm
* review readings from last class: query students about historical ecology of parasitism (Wood et al. 2023) and parasite conservation (Carlson et al. 2020)
* remind students that many of the [datasets available for their term project](https://wood-lab.github.io/fish_406/assignments.html#Term_project) pertain to long-term change in parasite populations
* today's parasite taxa are a grab bag: flatworms (Turbellaria, Fecampiida, and Monogenea) and cnidarians (Myxozoa)
* in-class activities shown in class_6.ppt
* Google Doc link for Q3 is [here](https://docs.google.com/document/d/1yWPt6tissjXtJJpPexAsLoK92WTMjE2jELDVLXuloWg/edit?usp=sharing)

<br>

## Class 7

Agenda:

* today we transition into the Class Cestoda
* remind students about tomorrow's lab, which will focus on cestodes
* remind students that they should be ready to present [a research question](https://wood-lab.github.io/fish_406/assignments.html#Term_project) in next week's lab (21 Oct)
* finish up in-class activities shown in class_6.ppt
* in-class activities shown in class_7.ppt

<br>

## Class 8

Agenda:

* ask students to recap yesterday's lab
* address William's question: why is *Kronborgia pugettensis* pink?
* remind students that they should be ready to present [a research question](https://wood-lab.github.io/fish_406/assignments.html#Term_project) in next week's lab (21 Oct)
* finish up in-class activities shown in class_7.ppt
* in-class activities shown in class_8.ppt

<br>

## Class 9

Agenda:

* remind students about week 3 quiz, due today at 11:59pm
* remind students that they should be ready to present [a research question](https://wood-lab.github.io/fish_406/assignments.html#Term_project) in next week's lab (21 Oct)
* today we make the transition to the nematodes
* there are a lot of videos assigned for today, so make sure you're caught up!
* finish up in-class activities shown in class_8.ppt
* in-class activities shown in class_9.ppt

<br>

## Class 10

Agenda:

* notify students of Canvas outage and remind them that they can access info about the course on this website, anytime
* remind students that lab will be held in FISH 106 tomorrow
* remind students that they should be ready to present [a research question](https://wood-lab.github.io/fish_406/assignments.html#Term_project) in TOMORROW'S lab (21 Oct)
* today we continue into the Phylum Nematoda
* define schmutzdecke (from Dickson's videos)
* finish up in-class activities shown in class_9.ppt
* in-class activities shown in class_10.ppt

<br>

## Class 11

Agenda:

* review yesterday's lab sections, in which students presented their [research questions](https://wood-lab.github.io/fish_406/assignments.html#Term_project)
* if you presented in lab, you will receive 1 point toward that assignment
* review next week's lab assignment: [preliminary analysis](https://wood-lab.github.io/fish_406/assignments.html#Preliminary_analysis), due Tuesday, 28 Oct
* remind students of [late policy](https://wood-lab.github.io/fish_406/assignments.html#Policy_on_late_assignments)
* remind students that the midterm is next week, Friday, 31 Oct
* practice midterm will be posted this week
* in-class activities shown in class_11.ppt

<br>

## Class 12

Agenda:

* remind students about week 4 quiz, due today at 11:59pm
* remind students about next week's lab assignment: [preliminary analysis](https://wood-lab.github.io/fish_406/assignments.html#Preliminary_analysis), due Tuesday, 28 Oct at 11:59pm
* remind students that the midterm is next week, Friday, 31 Oct
* practice midterm [is posted](https://wood-lab.github.io/fish_406/assignments.html#Exams)
* remind students that Wednesday's class will be a conversation with a real-life rat lungworm patient
* in-class activities shown in class_12.ppt

<br>

## Class 13

Agenda:

* remind students about the [preliminary analysis](https://wood-lab.github.io/fish_406/assignments.html#Preliminary_analysis) assignment **due tomorrow, 28 Oct at 11:59pm**
* remind students that the midterm is **this week, Friday, 31 Oct**
* clarify that there are no readings due on the day of the midterm (check the [Schedule](https://wood-lab.github.io/fish_406/schedule.html) tab to see which class number is assigned to which day)
* practice midterm [is posted](https://wood-lab.github.io/fish_406/assignments.html#Exams)
* remind students that Wednesday's class will be a conversation with a real-life rat lungworm patient and you [must watch the video ahead of time](https://wood-lab.github.io/fish_406/content.html#Class_14) - to access the video, you will need to either be on campus or use a VPN!
* distribute nasal strips + microscope slides for tomorrow's arthropod lab!
* in-class activities shown in class_13.ppt

<br>

## Class 14

Agenda:

* thank students for submitting [preliminary analysis](https://wood-lab.github.io/fish_406/assignments.html#Preliminary_analysis) and remind them of [late policy](https://wood-lab.github.io/fish_406/assignments.html#Policy_on_late_assignments)
* remind students that the midterm is **this week, Friday, 31 Oct**
* remind students of TA office hours posted [here](https://wood-lab.github.io/fish_406/syllabus.html#Instructors)
* live discussion with a real-life rat lungworm patient!

<br>

## Class 15

Agenda:

* exams are being graded and will be returned to you soon
* preliminary analysis assignments are in progress - you should already have received some feedback and you will soon receive more
* review findings of face mites and *Portunion conformis* in last week's lab
* ask that students send photos of lab findings - the best will be included on the course website (with attribution)
* remind students about the [introduction section assignment](https://wood-lab.github.io/fish_406/assignments.html#Introduction_section) due **tomorrow, Tueday, 4 Nov**
* remind students of the [late policy](https://wood-lab.github.io/fish_406/assignments.html#Policy_on_late_assignments)
* remind students that TA office hours are cancelled this week, but Chelsea is here and happy to meet with you!
* in-class activities shown in class_15.ppt

<br>

## Class 16

Agenda:

* exams grades will be released today, graded exam returned in Friday's class
* check out the feedback on your preliminary analysis assignment in Canvas
* review of Introduction sections is happening, feedback done by next week
* remind students about the [first draft assignment](https://wood-lab.github.io/fish_406/assignments.html#First_draft) due **Tuesday, 11 Nov**
* remind students that TA office hours are cancelled this week, but Chelsea is here and happy to meet with you!
* in-class activities shown in class_16.ppt

<br>

## Class 17

Agenda:

* graded exams will be returned at the end of class
* review of Introduction sections is happening, feedback done by next week
* remind students about the [first draft assignment](https://wood-lab.github.io/fish_406/assignments.html#First_draft) due **Tuesday, 11 Nov**
* remind students of Chelsea's office hours at 1:30pm this afternoon
* remind students that there is [**no class on Monday, 10 Nov**](https://wood-lab.github.io/fish_406/schedule.html) and [**no lab on Tuesday, 11 Nov (Veterans Day)**](https://wood-lab.github.io/fish_406/schedule.html) - please use this time to work on your first drafts!
* in-class activities shown in class_17.ppt

<br>

## Class 18

Agenda:

* if you have not yet picked up your graded exam, please see Chelsea
* review of Introduction sections is done, see Canvas for comments
* remind students about the [peer-review assignment](https://wood-lab.github.io/fish_406/assignments.html#Peer_review) due **Tuesday, 18 Nov**
* review upcoming deadlines as shown in [course schedule](https://wood-lab.github.io/fish_406/schedule.html)
* Gabby will be leading class this Friday, 14 Nov!
* in-class activities shown in class_18.ppt

<br>

## Class 19

Agenda:

* remind students about the [peer-review assignment](https://wood-lab.github.io/fish_406/assignments.html#Peer_review) due **Tuesday, 18 Nov**
* review upcoming deadlines as shown in [course schedule](https://wood-lab.github.io/fish_406/schedule.html): note final exam review is **Tuesday, 25 Nov** and poster presentations are **Tuesday, 2 December**
* bring dog poop to lab on Tuesday, 18 Nov!! (if you want; ABSOLUTELY no cat or raccoon poop)
* in-class activities shown in class_19.ppt

<br>

## Class 20

Agenda:

* remind students that ALL course content is found in the videos; if you are not watching and taking notes on the videos, you are missing the most important part of the course!
* remind students about the [peer-review assignment](https://wood-lab.github.io/fish_406/assignments.html#Peer_review) due **tomorrow, Tuesday, 18 Nov**
* review upcoming deadlines as shown in [course schedule](https://wood-lab.github.io/fish_406/schedule.html): note final exam review is **Tuesday, 25 Nov** and poster presentations are **Tuesday, 2 December**
* bring dog poop to lab on Tuesday, 18 Nov!! (if you want; ABSOLUTELY no cat or raccoon poop)
* in-class activities shown in class_20.ppt

<br>

## Class 21

Agenda:

* remind students that ALL course content is found in the videos; if you are not watching and taking notes on the videos, you are missing the most important part of the course!
* remind students about the [second-draft assignment](https://wood-lab.github.io/fish_406/assignments.html#Second_draft) due **Tuesday, 25 Nov**
* review this week's protozoa/poop lab
* remind students of the two assigned readings for this class
* in-class activities shown in class_21.ppt

<br>

## Class 22

Agenda:

* remind students that ALL course content is found in the videos; if you are not watching and taking notes on the videos, you are missing the most important part of the course!
* don't forget: you need to watch a whole movie (Contagion) for our next class session!
* remind students about the [second-draft assignment](https://wood-lab.github.io/fish_406/assignments.html#Second_draft) due **Tuesday, 25 Nov**
* big active day! We are going over the malaria life cycle, so make sure to take a look at it before class / if you miss class today!
* use feedback you recieved on your drafts from classmates and/or Chelsea to improve your drafts for next Tuesday!
* in-class activities shown in class_22.ppt

<br>

## Class 23

Agenda:

* remind students that ALL course content is found in the videos; if you are not watching and taking notes on the videos, you are missing the most important part of the course!
* remind students about the [second-draft assignment](https://wood-lab.github.io/fish_406/assignments.html#Second_draft) due **tomorrow, Tuesday, 25 Nov**
* tomorrow's **exam review lab** will be held in FISH 106 - please come with questions, especially ones about the [practice exam](https://wood-lab.github.io/fish_406/assignments.html#Exams)
* next week: you will present your term project in the form of a poster, which is due **Monday (NOT TUESDAY), 1 Dec at 11:59pm**
* next week: our final exam will be held **Friday, 5 Dec** during class time
* in-class activities shown in class_23.ppt

<br>

## Class 24

Agenda:

* no class this Friday, 28 Dec (see [course schedule](https://wood-lab.github.io/fish_406/schedule.html)), but **don't forget that the week 9 quiz is due on Friday, 28 Dec**
* next week: you will present your term project in the form of a poster, which is due **Monday (NOT TUESDAY), 1 Dec at 11:59pm**
* see the [course website](https://wood-lab.github.io/fish_406/assignments.html#Poster_presentation) for details on how to prepare your poster
* [second-draft assignments](https://wood-lab.github.io/fish_406/assignments.html#Second_draft) will be returned with instructors' comments by Tuesday, 2 Dec
* next week: our final exam will be held **Friday, 5 Dec** during class time
* in-class activities shown in class_24.ppt

<br>

## Class 25

Agenda:

* tomorrow: you will present your term project in the form of a poster, which is due **today, Monday (NOT TUESDAY), 1 Dec at 11:59pm**
* see the [course website](https://wood-lab.github.io/fish_406/assignments.html#Poster_presentation) for details on how to prepare your poster
* [second-draft assignments](https://wood-lab.github.io/fish_406/assignments.html#Second_draft) will be returned with instructors' comments by Tuesday, 2 Dec
* our final exam will be held **Friday, 5 Dec** during class time
* if 90% of enrolled students complete these our two course evaluations, I will add a 5-point bonus question to the final! links are in [Canvas announcements](https://canvas.uw.edu/courses/1829825/discussion_topics/10126495?is_announcement=true)
* if you're taking the exam in DRS Center, drop off your lab notebook after you're done, in Chelsea's office (318B)
* in-class activities shown in class_25.ppt

<br>

## Class 26

Agenda:

* nice job on your posters!
* use comments on your [second-draft assignments](https://wood-lab.github.io/fish_406/assignments.html#Second_draft) to improve your draft ahead of the final draft submission deadline of **Thursday, 11 Dec**
* our final exam will be held **Friday, 5 Dec** during class time
* if you're taking the exam in DRS Center, drop off your lab notebook after you're done, in Chelsea's office (318B)
* if 90% of enrolled students complete these our two course evaluations, I will add a 5-point bonus question to the final! links are in [Canvas announcements](https://canvas.uw.edu/courses/1829825/discussion_topics/10126495?is_announcement=true)
* in-class activities shown in class_26.ppt

<br>

# Rules for TAs

<br>

## Preparing for the quarter

In preparation to TA FISH 406, TAs should do the following:

* take the appropriate training to obtain access the UW vivarium (talk to Chelsea about how to get this started)
* familiarize yourself with all [course content](https://wood-lab.github.io/fish_406/content.html), including readings and videos
* read Combes' [*Parasitism: The Ecology and Evolution of Intimate Interactions*](https://press.uchicago.edu/ucp/books/book/chicago/P/bo3634576.html)
* read Karban, Huntzinger, and Pearse's [*How to Do Ecology: A Concise Handbook*](https://press.princeton.edu/books/paperback/9780691245751/how-to-do-ecology?srsltid=AfmBOoqDA_JF2dhFDKJevtALXsb9URJZm95La6d6NUBzs3Jn7xe7COaZ)
* read Roberts and Janovy's [*Foundations of Parasitology*](references/R&J.pdf)
* work with the SAFS Facilities Manager to move all [equipment and supplies](https://wood-lab.github.io/fish_406/instructors_corner.html#Supplies_needed_for_labs) into the teaching lab
* check over the [stockpile of teaching supplies](https://wood-lab.github.io/fish_406/instructors_corner.html#Supplies_needed_for_labs) and let Chelsea know if we are running low on anything
* prepare living materials for the first few labs (especially the living schistosome-infected mice that are used in Lab 1)
* set up the lab so that it is ready for students (e.g., arrange benches, microscopes, dissection tools, slides)
* tune up the microscopes so that they are ready for students (e.g., clean optics, tighten screws)
* check the agreement between the course website and Canvas site, especially screening for date discrepancies
* consider whether and which class sessions you would like to lead, and let Chelsea know

<br>

## Office hours

Each TA is required to hold one regularly scheduled 60-minute office hour per week. Before the quarter starts, please tell Chelsea when you'd like to hold your office hour, and she will update the course website accordingly. If you must cancel your office hour (e.g., due to illness), you are required to hold a make-up office hour as soon as possible thereafter. When students are not available during regularly scheduled office hours, TAs are required to make themselves available for meetings by appointment.

<br>

## Instructional personnel meetings

FISH 406 TAs are required to make themselves available for weekly 30-minute instructional personnel meetings, where we prepare for the coming week's labs, events, and assignments. Usually, these meetings are held in the 30 minutes following class every Friday (1:30-2pm).

<br>

## Travel

TAing FISH 406 is a commitment and we take our responsibility to students very seriously. FISH 406 TAs are therefore not permitted to engage, during the quarter of their TAship, in any travel that would interfere with their ability to attend lecture, lab sessions, or regularly scheduled office hours. This includes field work and conference travel in addition to personal travel. No vacation or holiday time may be taken when classes are in session during the quarter of a FISH 406 TAship. Outside of the weeks when classes are in session, vacation and holiday time requests will be approved only if these requests do not interfere with FISH 406 commitments (e.g., preparing laboratory space for the quarter, grading final exams). This allows the instructional staff of the course to dedicate the time and attention that our students deserve.

<br>

## Grading

In FISH 406, TAs are empowered to contribute to grading (e.g., lab notebooks, exams), but final decision-making authority rests with the instructor of record (Chelsea). TAs are expected:

* to be familiar with all course policies, especially those that [pertain to grading](https://wood-lab.github.io/fish_406/assignments.html#Grading),
* to avoid misinforming students about these policies, and 
* to point students to these policies when needed. 

TAs are strictly forbidden from changing student grades without first consulting Chelsea; if it is discovered that a TA has changed a grade without first consulting Chelsea, Canvas gradebook privileges will be removed from all TAs and the TA who broke the rule will become ineligible for future FISH 406 TAships.

<br>

## Norming

One of the most important duties of a FISH 406 TA is to provide feedback to students on their work: on exams, independent research projects, and presentations. To make sure that we are providing equal levels of support across students and grading by the same standards, the FISH 406 instructional team will periodically engage in "norming" exercises. When we "norm" our feedback for a given assignment, we will all get together to evaluate the same few assignments, compare our feedback, and discuss how to bring our feedback into alignment. We continue doing this until the instructor of record (Chelsea) is satisfied that every member of the instructional team is on the same page. This may be repeated for each exam/assignment. 

<br>

# How to order mice

* All animal imports are handled by the Rodent Health Monitoring Program / Animal Purchasing in the Department of Comparative Medicine.
* All requests must be submitted through the online system AOps (which is administered via Hoverboard) - step-by-step instructions are [here](https://s3-us-west-2.amazonaws.com/uw-s3-cdn/wp-content/uploads/sites/160/2019/12/27215534/AOps-How-to-Initiate-an-Animal-Order.pdf).
* Do you already have a registration for BEI Resources? You will need this to order the mice. If not, start this as early as possible - it is a [long process](https://www.beiresources.org/RegisterLevel2.aspx) that requires many documents.
* Start by touching base with Margaret Mentink-Kane at BRI (mmentinkkane@afbr-bri.org). 

  - Tell her what you want to do ahead of time to give her a heads-up. 
  - Ask her for the latest BRI health reports (see below). 
  - Figure out the timing. Mice should be six weeks post-infection (five weeks post-receipt at UW) when they are euthanized. That means that if your lab is scheduled for 6 Oct, the mice should be infected on 25 Aug and shipped on 1 Sep. The IACUC protocol says that the mice should be euthanized within 5 weeks of receipt, so stick to that. The earlier you euthanize, the fewer/smaller worms. The later you euthanize, the sicker the mice get, and the likelier they are to suffer and die. Five weeks post-receipt seems like the right balance.

* You’ll have to obtain three documents:

  - Health reports from BEI (these need to be dated within three months of the date of request submission) to demonstrate that mice are free of pathogens that could spread in the vivarium
  - Material Transfer Agreement signed by CoMotion (the one from 2017 can be re-used)
  - Invoice or price quote for shipping charges (the one from 2017 can be re-used)

* Once you have all the materials needed to place your order, sign into Hoverboard. Click the Animal Operations tab at the top. Then select the relevant IACUC protocol. There should be an “order animals” button at left.

  - If there isn’t, it’s because your protocol hasn’t been activated for animal orders yet. Contact billing@uw.edu and cc animals@uw.edu, give them protocol number and budget number (the SAFS teaching budget worktags are in LastPass), and ask if the IACUC protocol can be activated for ordering animals.

  - If there is a button, click “Order Animals”
    - Select mice
    - 25 animals
    - 5 animals / cage
    - Financial account = SAFS teaching budget worktags
    - Will these animals require special ordering, handling, or housing information? No
    - Catalog or stock number = NR-21963
    - Select the highlighted strain
    - Sex = female
    - Age/weight = NA
    - Room = N039B, Foege ABSL2 room
    - Click through
    - Other vendor information = BEI Resources, 10801 University Boulevard, Manassas, VA 20110-2209, Enter Margaret’s contact information in all fields
    - On the final window, attach all files and write this in the comments: “This is an order for 25 schistosomiasis-infected mice from BEI Resources (NR-21963 Schistosoma mansoni, Strain NMRI, Exposed Swiss Webster Mice). I have attached recent health reports from BEI Resources, the Material Transfer Agreement, and a quote for shipping. Please don't hesitate to reach out if you need any additional documentation to process this request (Chelsea Wood, 831-324-3076, chelwood@uw.edu).” 
    - ALSO ADD TO COMMENTS: “DCM is only covering the courier fees and I will pay for the order fee online.” 
    - Attach Kris Blow’s e-mail (import@uw.edu) confirming that it is okay for me to place the order myself.

* Once you obtain approval via Hoverboard, DCM Animal Purchasing will send a shipment approval pdf and get the PO set up.

  - DCM Animal Purchasing should send the shipment approval pdf and PO to both me and to our order contact (Margaret Mentink-Kane at BEI) by e-mail, and then you can respond to that e-mail with exact specifications.
  - DCM Animal Purchasing will need to be cc’d on all order changes, updates, etc, so please leave them on the email strain. This will satisfy the legal and by-law requirements for DCM to handle the order, but also ensure you are getting the proper mice for your class.

* Be aware that DCM prefers that DCM staff order animals directly from the supplier (BEI Resources).
  - DCM prefers to do all ordering/paying themselves.
  - However, this is really hard with BEI Resources, because you have to register for an individual account to place orders on their website. As you'll see from the BEI website, [registering for an account is not straightforward](https://www.beiresources.org/RegisterLevel2.aspx). If there is personnel turnover in DCM, the next person would need a different account and would need to go through the registration process all over again. Ordering is also not very straightforward, and I much prefer to do it myself to ensure that the exact items needed are the ones that are received. To register a new account, you would need to obtain a new Material Transfer Agreement from CoMotion. You would also need a new biosafety level 2 checklist for my facility (we would need to get a new inspection if you establish a new account).
  - However, they have  agreed to allow us to continue placing our own orders, under the following conditions: “As long as the imports are still processed by DCM and you wait to place the order with BEI until after we have sent the shipment approval, there should be no issue. When submitting orders in AOps, please put a note that DCM is only covering the courier fees, and that you are taking care of the charge for the order fee online. If you want, save this email and send it along as an attachment if questions arise. I will remember this from the note on the Aops order, but you are correct that future Order coordinators may not be aware of this agreement. We accept that this is a rare occurrence and I can vouch that your method is simpler and allows for the correct items to be requested. As long as we have the records and authorizations in place, this is acceptable.” (Kris Blow, import@uw.edu, 30 July 2020)

* After DCM Animal Purchasing approves your order, you can place the order in BEI Resources.

  - You must be registered with BEI Resources to order. If you are not registered, go through the registration process to get log-in details.
  - Enter login information.
  - Search catalog number NR-21963 (Schistosoma mansoni, Strain NMRI, Exposed Swiss Webster Mice).
  - Add to cart.
  - Enter quantity = 25
  - Select shipping destination = 3720 15th Ave NE
  - Enter building information = Foege Loading Dock, N030
  - No need to add comments
  - Make sure that you copy import@uw.edu, animals@uw.edu, billing@uw.edu (tick All Additional Order Correspondence)
  - Enter payment information (can use purchasing card)
  - In the Standing Order form, write “once” and “1” to indicate that this is a one-time order.
  - Submit, print, and retain order receipt.

* After the order is successfully placed, make sure that you have current access to the ARCF (i.e., the Foege vivarium), so that you can take care of the mice when they arrive.

  - You need to [renew your access annually](https://research.washington.edu/research/required-training/annual-animal-use-training-for-rodent-users/) by taking an online course via the Animal Use Training Program. The course is called Annual DCM Facility Access Training (Rodent).
  - If you let your facility access lapse for more than three months, you’ll need to re-do the in-person orientation to the facility. Contact auts@uw.edu to schedule this.
  - Once you are renewed, your Husky card will give you access to the vivarium. 

* When the mice arrive at the vivarium, the courier won’t be able to get into the building. They will have Chelsea’s phone number, and will probably call Chelsea. To get the mice properly received, call Olena or Cory and ask them to go out to the loading dock to receive the mice:

  - Program Coordinators: Olena Iatsenko (206-221-4239)   /  Cory Conner (206-616-4577)

* When World Courier sends you an invoice for the mice

  - You can pay with your purchasing card
  - Call the number at the bottom of the World Courier e-mail to pay

<br>



# How to care for and euthanize mice

1. Mice will be shipped by BRI and should arrive at the Foege loading dock, where they will be received by vivarium staff.Staff will then house the mice and indicate the room and rack in Hoverboard.

2. Don’t count on getting a notification when the mice arrive. Check Hoverboard to find out whether they have made it or not and follow up accordingly. Note that only the person who actually places the mouse order (i.e., Chelsea) can check this in Hoverboard, and usually this same person will receive the tracking information from BRI / the freight company.

3. As soon as mice arrive in the vivarium, our IACUC protocol requires that we check on them. Vivarium staff will check on the general well-being of the animals, but we are responsible for making sure that they are not exhibiting any signs of severe intestinal schistosomiasis:

* body condition
* respiratory effort
* hair coat
* activity
* fecal output

4. How to enter the vivarium:

* Make sure that you are wearing close-toed shoes and long pants.
* Use your Husky card to enter the Foege main door, then take the elevator to B.
* Use your Husky card to enter the main door of the vivarium (to your left when you exit the elevator) and the secondary door of the vivarium (to your left as you pass through the main door).
* Take a pair of scrubs from the rack.
* Proceed to the locker rooms (down the hallway to your left as you enter the vivarium).
* Take off your street clothes (underwear/undershirt/socks okay to leave on) and place them in one of the lockers.
* Put on scrubs.
* Proceed through the airlock.
* Put on a hair net and sanitary booties.
* Open the door on the other side and select a pair of crocs from the rack.
* Proceed to the room where the mice are housed.
* Put in your personal 4-digit code to access the room.
* If your pin doesn’t work, consult Olena, whose office is located near the clean cages (as you enter the rodent side of the vivarium, turn right out of the locker rooms and right at the clean cages, and you’ll see her office in front of you).

5. Mice should be checked once per week in the first three weeks and twice per week in the last two weeks.

6. Check the mice using these criteria:

* body condition
* respiratory effort
* hair coat
* activity
* fecal output

7. If any mice appear to be in distress, alert the vivarium veterinarian immediately.

8. How to euthanize the mice:

* Remember to bring a small hand-held cooler with you. This can be placed in the ante room as you enter the vivarium (the room to the left of the doors to the locker rooms).
* Remove the cages from the rack and carry them to an empty procedure room. Any room with a hood and a cage lid equipped with a port for CO2 will do.
* If you only want to euthanize a subset of the mice in a given cage, remember that the survivors shouldn’t watch the euthanasia take place. Grab a clean cage from the rack in front of the vivarium offices (the hallway to your right as you exit the locker rooms into the vivarium), put the subset of mice that you want to euthanize in the clean cage, and return the survivors to their rack in their original cage.
* When moving live mice, pick them up by their tails.
* There should be no more than five mice in a cage at any time, including during euthanasia.
* Place the cage of mice that you want to euthanize in the hood.Turn the hood on (press the “flow on” button and then the “light on” button).
* Remove the cage lid and the feeding grate and place them next to the cage in the hood.Place the metal cage lid with a port for CO2 on top of the cage.
* Open the CO2 valve (inside the hood).
* Turn the dial to 2.1 (or whatever is indicated on the sign above the valve on the wall next to the hood).
* Set the timer for 5 minutes.
* While you’re waiting, remove the cage tag. The tear-off portion at the top needs to be put into the folder on the back of the door in the housing room. This tells the vivarium to stop charging us per-diem (because the cage of mice is no longer in the housing room).
* Grab a body bag from the drawer in the procedure room.Place the cage tag (without tear-off portion at the top) inside the bag.
* Remember that gas flow must be maintained for at least 1 minute after clinical death. Watch for breathing and twitching. Once this stops, give the mice at least 1 more minute in the chamber. Note: Euthanization can sometimes take longer than 5 minutes! 
* Once mice are dead, remove the metal cage lid.
* Lift the mice by their tails and check for signs of life (i.e., feel for heartbeat, or lightly pinch the foot to look for reflexes). If no signs of life are observed, place the mice into the body bag, along with the cage tag.
* Once all mice are in the body bag, hold the bag up to the CO2 port in the metal lid to fill the bag with CO2. This is a secondary method of euthanasia - if the mice wake up, they will be in a bag full of CO2 and will die.
* Once the bag is full of CO2, tie it off.
* Clidox all surfaces thoroughly.
* Place the empty cage on the “dirty cage rack”.
* Place the bag of mice inside your cooler in the ante room.
* Proceed back the way you came, through the locker room. Change into street clothes.
* Grab the cooler from the ante room and leave the vivarium with your mice.

<br>


<center>*This site was last updated at `r format(Sys.time(), "%H:%M")` on `r format(Sys.Date(), "%d %b %Y")`*</center>
